application: maisalabs
version: 79
runtime: php
api_version: 1

handlers:
- url: /img
  static_dir: img
  application_readable: true

- url: /css
  static_dir: css
  application_readable: true

- url: /js
  static_dir: js
  application_readable: true

- url: /sitemap.xml
  static_files: sitemap.xml
  upload: sitemap.xml

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /(.+)\.(.+)
  script: \1.\2

- url: /
  script: index.php
